### ISSUE TITLE
How is the latent vector z coupled to the generator?

### ISSUE THREAD

**Issue by Ouwen** [maga33/DSGAN#1]
Hello, I've been reading your paper and was wondering how the latent z vector is coupled to the generator. Without digging through the code, I am assuming you are using the same scheme as in BicycleGANs. Is this correct?

![image](https://user-images.githubusercontent.com/5455421/60852299-1d142700-a1c5-11e9-8618-f452decf6e0a.png)

Very nice work, and thanks.

**Comment by maga33** [comment]
Hi Ouwen,

Yes, you are correct. We are using the same BicycleGAN generator/discriminator architectures in Image-to-Image translation task. 

I also would like to note that our diversity-sensitive regularization can be applied independently with the choice of generator architecture (e.g. conditioning on the latent variable). For instance, we used different backbone generator networks for image inpainting and video prediction tasks. The basic principles to apply our regularization are 1) choosing reasonable generator/discriminator that produce reasonable output samples (mode-collapse is fine; our regularization will fix it). 2) adding our regularization to the generator objective, 3) tuning a hyper-parameter (\lambda) to achieve the best realism/diversity by monitoring FID and LPIPS scores. Please note that adding our regularization to existing (conditional) GAN models requires only a few lines of modifications.

**Comment by Ouwen** [comment]
Did the method of z coupling matter? For example, did you get different realism scores for the left vs right schemes above?

**Comment by santisy** [comment]
Hi @Ouwen , we did not study the effect of different latent vector injection methods.

As @maga33 suggests, as long as the latent vector injection methods have been proved reasonable in previous literatures, it should be okay. In other words, if there is any difference in realism scores by different injection methods, it may largely relate to the injection method itself.

**Comment by Ouwen** [comment]
@santisy @maga33 thanks for the clarification. I also wanted to compliment the work. I am a fan of the elegance of your approach.
